// Generates packages/engine/src/ui/theme.css: every Material 3 colour role, light and dark, from one seed.
// Run after changing the seed:  pnpm exec tsx scripts/make-theme.mjs
// The seed is the gingerbread avatar's own baked-in brown (sampled from the rendered frame), not Material's
// baseline purple, so the interface takes its colours from the thing it is showing.
import { writeFileSync } from "node:fs";
import { Hct, MaterialDynamicColors, SchemeTonalSpot, argbFromHex, hexFromArgb, blueFromArgb, Blend } from "@material/material-color-utilities";

const SEED = "#AE6E3A";
// Status colours Material has no role for. Blended toward the seed so they sit in the same palette.
const CUSTOM = [
  ["success", "#3F8F4A"],
  ["warning", "#B8860B"],
];

const kebab = (s) => s.replace(/_/g, "-").replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase();

/** Every DynamicColor Material defines, as { "surface-container-high": "#rrggbb" }. */
function roles(isDark) {
  const scheme = new SchemeTonalSpot(Hct.fromInt(argbFromHex(SEED)), isDark, 0);
  const out = {};
  for (const [key, value] of Object.entries(MaterialDynamicColors)) {
    if (value && typeof value === "object" && typeof value.getArgb === "function" && value.name) out[kebab(value.name)] = hexFromArgb(value.getArgb(scheme));
  }
  // Custom colours: Material's own recipe (tone mapping per mode) applied to a blended hue.
  for (const [name, hex] of CUSTOM) {
    const blended = Blend.harmonize(argbFromHex(hex), argbFromHex(SEED));
    const hct = Hct.fromInt(blended);
    const tone = (t) => hexFromArgb(Hct.from(hct.hue, Math.max(hct.chroma, 36), t).toInt());
    out[name] = tone(isDark ? 80 : 40);
    out[`on-${name}`] = tone(isDark ? 20 : 100);
    out[`${name}-container`] = tone(isDark ? 30 : 90);
    out[`on-${name}-container`] = tone(isDark ? 90 : 10);
  }
  return out;
}

const block = (r, indent) => Object.entries(r).map(([k, v]) => `${indent}--md-sys-color-${k}: ${v};`).join("\n");
const light = roles(false), dark = roles(true);

const css = `/* GENERATED by scripts/make-theme.mjs from seed ${SEED}. Do not edit by hand. */
:root {
  color-scheme: light dark;
${block(light, "  ")}
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${block(dark, "    ")}
  }
}
:root[data-theme="dark"] {
  color-scheme: dark;
${block(dark, "  ")}
}
`;
writeFileSync(new URL("../packages/engine/src/ui/theme.css", import.meta.url), css);
console.log(`wrote theme.css: ${Object.keys(light).length} roles, seed ${SEED}`);
console.log(" primary", light.primary, "/", dark.primary, " surface", light.surface, "/", dark.surface, " success", light.success, " warning", light.warning);
